general.import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml" # zsh, bsh
    #"~/AppData/Roaming/alacritty/themes/themes/gruvbox_dark.toml" # pwsh
]

general.live_config_reload = true

[font]
normal = { family = "GohuFont14 Nerd Font"} #, style = "Italic" }
size = 12
#builtin_box_drawing = true 

#[window]
#dimensions = { columns = 100, lines = 40 }

#padding = { x = 3, y = 3 }
#dynamic_padding = true

#startup_mode = "Windowed"
#title = "Alacritty"
#dynamic_title = true 
#decorations_theme_variant = "None"
#decorations = "Buttonless"
#opacity = 0.9
#blur = true

# Set environment variables
#[env]
#TERM = xterm-256color

#shell = "zsh"
