# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"

# Fix escape time
set -sg escape-time 0

# Set prefix
unbind C-b
set -g prefix C-o
bind C-o send-prefix

# Load plugins
# set -g @plugin 'catppuccin/tmux'
#set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin "https://gitlab.com/motaz-shokry/gruvbox-tmux"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Set gruvbox theme
#set -g @tmux-gruvbox 'dark' # or 'light'
set -g @gruvbox-tmux_theme "soft"     # light | medium | soft | Default is hard
set -g @gruvbox-tmux_transparent 0    # 1 | 0
set -g @gruvbox-tmux_show_battery_widget 0     # 0 to disable
set -g @gruvbox-tmux_battery_name "BAT0"       # run `ls /sys/class/power_supply` to know
set -g @gruvbox-tmux_battery_low_threshold 25 


# True color fix
#set-option -a terminal-features 'tmux-256color:RGB'
set-option -a terminal-features 'tmux-256color:RGB'

# Run tmux plugin manager
run '~/.tmux/plugins/tpm/tpm'
